# Generated by Django 4.2.7 on 2023-12-27 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imgs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
